# Generated by Django 3.0.10 on 2020-09-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_enhance_item_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, verbose_name='code')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('expiry_date', models.DateField(verbose_name='Expiry Date')),
            ],
        ),
    ]
