# Generated by Django 3.0.10 on 2020-09-09 14:24

import app.orders.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to=app.orders.models.Item.product_image_path, verbose_name='Product Image'),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Refund Code'),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('IN', 'initiated'), ('DE', 'delivered'), ('RE', 'received'), ('RR', 'Refund Request'), ('RG', 'Refund Granted')], default='IN', max_length=2, verbose_name='Order State'),
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('accepted', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
        ),
    ]
